//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRate
    {
        public int RateId { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> TourId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblCat tblCat { get; set; }
        public virtual tblTour tblTour { get; set; }
    }
}
